// src/Components/Checkboxes.tsx
import * as React from 'react';
import type GraphAnalysisPlugin from '../main';
import type { Subtype } from '../Interfaces';

interface CheckboxesProps {
  options: Subtype[];
  plugin: GraphAnalysisPlugin;
  settingName: 'algsToShow';
}

const Checkboxes: React.FC<CheckboxesProps> = ({
  options,
  plugin,
  settingName,
}) => {
  const [selected, setSelected] = React.useState<Subtype[]>(
    plugin.settings[settingName]
  );
  const [hasSelection, setHasSelection] = React.useState(selected.length > 0);

  React.useEffect(() => {
    setHasSelection(selected.length > 0);
    // 선택 상태 변경 시 설정 자동 저장
    plugin.settings[settingName] = selected;
    plugin.saveSettings();
  }, [selected]);

  const handleChange = (option: Subtype) => {
    const newSelected = selected.includes(option)
      ? selected.filter((item) => item !== option)
      : [...selected, option];
    setSelected(newSelected);
  };

  const handleToggleAll = () => {
    const newSelected = hasSelection ? [] : options; // hasSelection이 true면 전체 해제
    setSelected(newSelected);
  };

  return (
    <div className='ga-mb-2 mb-2'>
      <button onClick={handleToggleAll}>
        Select {hasSelection ? 'None' : 'All'}
      </button>
      <div className="GA-grid">
        {options.map((option) => (
          <div key={option}>
            <label>
              <input
                type="checkbox"
                checked={selected.includes(option)}
                onChange={() => handleChange(option)}
              />
              {option}
            </label>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Checkboxes;

// src/Components/Checkboxes.svelte
<script lang="ts">
  import AnalysisView from '../AnalysisView'

  import type GraphAnalysisPlugin from '../main'

  export let plugin: GraphAnalysisPlugin
  export let settingName: string
  export let options: string[]
  // @ts-expect-error
  let selected = plugin.settings[settingName] as string[]

  let toNone = selected.length === 0 ? false : true
  $: toNone = selected.length === 0 ? false : true

  async function save() {
    // @ts-expect-error
    if (plugin.settings[settingName] === undefined) {
      return console.log(settingName + ' not found in BC settings')
    }


    // @ts-expect-error
    plugin.settings[settingName] = selected
    await plugin.saveSettings()
  }
</script>

<div>
  <button
    on:click={async () => {
      if (toNone) selected = []
      else selected = options

      await save()
    }}
  >
    Select {toNone ? 'None' : 'All'}
  </button>
</div>

<div class="grid">
  {#each options as option}
    <div>
      <label>
        <input
          type="checkbox"
          value={option}
          bind:group={selected}
          on:change={async () => save()}
        />
        {option}
      </label>
    </div>
  {/each}
</div>

<style>
  .grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    /* grid-gap: 10px; */
  }
</style>
